language: node_js

node_js:
  - "9"

cache:
  directories:
  - node_modules
  - client/node_modules

addons:
  chrome: beta
  firefox: latest

script:
  - yarn typecheck
  - yarn lint
  - yarn test
  - yarn checkdeps
  - yarn checklangs
  - cd client
  - yarn lint
  - yarn build
